dist : trusty
language: java
jdk:
  - oraclejdk8
sudo: required
env:  
  global:
    - MAVEN_SETTINGS="${TRAVIS_BUILD_DIR}/gsi-config"
    - MAVEN_OPTS="-Xms1g -Xmx2g" 
  matrix: 
    - JOB=SONAR
    - JOB=UNIT_TEST
    - JOB=PLAIN_WEB_IT
    - JOB=BULK_WEB_IT
    - JOB=OTHER_WEB_IT
    - JOB=RUNSCANNER_TEST
    - JOB=PINERY_IT

git:
  depth: 3

addons:
    sonarcloud:
        organization: "miso-lims"
        token:
            secure: "CuaZUL0SJiRQR3Z+zvSTKAJc+/SOC+2g5a9gG08NYYSkwN8Ujwoyd9e14DLuyFaY2xZppQb5OIcQWQH+lmZqZbycRuAlBsTy1iIooUFB9v80g5eW8RDaJu3609Y7emSV7sZ3wuTJx3sTDeITAbkhRz0FQ2FyyoFMgD1jI+lxPXA="
        github_token:
            secure: "PsRH/x31KHGk/l0QlwMLDj437bKnWxJF45o2AiYZofVQZRVXzhhhpVxMqMl3QZ25K8wq5Qr7F2a2MYdMHtUpl0RBL5TWMDTmP9T1hyjA8IuqYx8Lq2ZklOvB4HJa/HgZEGVRWDyl4XE3giVDsYxPNogFTD1ieE6rs3XC0KkhQWY="
        branches:
            - develop

before_install:
    - git clone https://github.com/oicr-gsi/gsi-config.git "${MAVEN_SETTINGS}"
    - cp "${MAVEN_SETTINGS}/settings.xml" "${HOME}/.m2/settings.xml"
    - 'echo pr slug ${TRAVIS_PULL_REQUEST_SLUG} && echo repo slug ${TRAVIS_REPO_SLUG}'

before_script:
  - export MAVEN_OPTS='-Xms1g -Xmx2g' CXX=g++-5
  - sudo apt-add-repository -y ppa:likemartinma/devel
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install -y pkg-config cmake libjsoncpp-dev autoconf libtool build-essential gcc-5 g++-5

script: ./travis_jobs.sh

cache:
  directories:
    - "$HOME/.sonar/cache"
    - "$HOME/.m2"

notifications:
  email: false
  slack:
    rooms:
      secure: KoPcna/UJ0krX0nZhWh0icgTslfvJfnOj+pSphRRhfy0AsZ75vU281yfNlNd+nlkoCQYxW9/a4vleSMpGONunnKm+i2/XHEaUFpdbR9+aQJZj1tDss+osSAoJhREtAMLTJ2CDyVjkfE5OAFdw/d9vkYFFk+ZPl7YcswOpivkqvs=
    on_success: change
    on_failure: always

