version: '3.7'

# .env file or shell environment variables should contain the following: 
# MISO_DB_USER : name of the MySQL user who accesses MISO_DB [tgaclims]
# MISO_DB : name of the LIMS Db in MySql [lims]
# MISO_DB_PASSWORD_FILE : path to the file with the password to the MySQL DB for user MISO_DB_USER

secrets:
  lims_password: 
    file: ${MISO_DB_PASSWORD_FILE}

services:

  db:
    image: mysql:5.7.25
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ${MISO_DB}
      MYSQL_USER: ${MISO_DB_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/lims_password
    volumes:
      - "miso_db:/var/lib/mysql"
    secrets:
      - lims_password

  flyway:
    restart: on-failure
    build:
      context: .
      target: flyway-migrate
      args:
        FLYWAY_VERSION: 3.2.1
    environment:
      MISO_DB_USER: ${MISO_DB_USER}
      MISO_DB: ${MISO_DB}
      MISO_DB_URL: 'db:3306'
      MISO_DB_PASS_FILE: /run/secrets/lims_password
      MISO_FILES_DIR: /storage/miso/files/
    secrets:
      - lims_password
    links:
      - db
    depends_on:
      - db

  webapp:
    restart: always
    build:
      context: .
      target: webapp
    ports: 
      - "8090:8080"
    environment:
      MISO_DB: ${MISO_DB}
      MISO_DB_USER: ${MISO_DB_USER}
      MISO_DB_PASS_FILE: /run/secrets/lims_password
    secrets:
      - lims_password
    volumes:
      - "./.docker/tomcat/setenv.sh:/usr/local/tomcat/bin/setenv.sh"
      - "miso_files:/storage/miso/files/"
    links:
      - db
      - flyway
    depends_on:
      - db
      - flyway


volumes:
  miso_db:
  miso_files: